import { Types } from 'mongoose';

// Tạo một số ID cố định để tham chiếu
const generateId = () => new Types.ObjectId().toString();

// IDs cố định cho các thế hệ đầu tiên
const rootId = generateId(); // Thủy tổ (Đời 1)
const gen2Child1Id = generateId(); // Con đầu của thủy tổ
const gen2Child2Id = generateId(); // Con thứ của thủy tổ
const gen2Child3Id = generateId(); // Con thứ của thủy tổ

// Tạo dữ liệu mẫu cho 7 đời với nhiều nhánh
export const FAMILY_MEMBERS_SAMPLE = [
  // Đời 1 - Thủy tổ
  {
    _id: rootId,
    fullName: 'Nguyễn Văn Thủy Tổ',
    gender: 'MALE',
    dateOfBirth: new Date('1800-01-15'),
    lunarDateOfBirth: '15/01/Canh Thân',
    dateOfDeath: new Date('1880-07-22'),
    lunarDateOfDeath: '22/07/Canh Thìn',
    hometown: 'Làng Cổ Tích, Hà Nam',
    biography: 'Thủy tổ họ Nguyễn, người lập nghiệp và xây dựng dòng họ từ những năm đầu thế kỷ 19.',
    generation: 1,
    isActive: true,
  },
  
  // Đời 2 - 3 người con của thủy tổ
  {
    _id: gen2Child1Id,
    fullName: 'Nguyễn Văn Trưởng',
    gender: 'MALE',
    dateOfBirth: new Date('1830-03-10'),
    lunarDateOfBirth: '10/03/Canh Dần',
    dateOfDeath: new Date('1900-09-05'),
    lunarDateOfDeath: '05/09/Canh Tý',
    hometown: 'Làng Cổ Tích, Hà Nam',
    fatherId: rootId,
    biography: 'Con trai trưởng của thủy tổ, người kế tục và phát triển sự nghiệp của cha.',
    generation: 2,
    isActive: true,
  },
  {
    _id: gen2Child2Id,
    fullName: 'Nguyễn Văn Thứ',
    gender: 'MALE',
    dateOfBirth: new Date('1835-08-22'),
    lunarDateOfBirth: '22/08/Ất Mùi',
    dateOfDeath: new Date('1905-11-15'),
    lunarDateOfDeath: '15/11/Ất Tỵ',
    hometown: 'Làng Cổ Tích, Hà Nam',
    fatherId: rootId,
    biography: 'Con trai thứ hai của thủy tổ, người nổi tiếng về tài văn chương.',
    generation: 2,
    isActive: true,
  },
  {
    _id: gen2Child3Id,
    fullName: 'Nguyễn Thị Hiền',
    gender: 'FEMALE',
    dateOfBirth: new Date('1838-12-05'),
    lunarDateOfBirth: '05/12/Mậu Tuất',
    dateOfDeath: new Date('1910-04-20'),
    lunarDateOfDeath: '20/04/Canh Tuất',
    hometown: 'Làng Cổ Tích, Hà Nam',
    fatherId: rootId,
    biography: 'Con gái út của thủy tổ, người nổi tiếng về đức hạnh và tài nữ công.',
    generation: 2,
    isActive: true,
  },
  
  // Đời 3 - Con cháu của 3 người con đời 2
  // Con của Nguyễn Văn Trưởng
  {
    _id: generateId(),
    fullName: 'Nguyễn Văn Hiếu',
    gender: 'MALE',
    dateOfBirth: new Date('1855-05-20'),
    lunarDateOfBirth: '20/05/Ất Mão',
    dateOfDeath: new Date('1925-08-10'),
    lunarDateOfDeath: '10/08/Ất Sửu',
    hometown: 'Làng Cổ Tích, Hà Nam',
    fatherId: gen2Child1Id,
    biography: 'Con trai trưởng của Nguyễn Văn Trưởng, nối nghiệp cha về nghề nông.',
    generation: 3,
    isActive: true,
  },
  {
    _id: generateId(),
    fullName: 'Nguyễn Văn Tài',
    gender: 'MALE',
    dateOfBirth: new Date('1858-10-30'),
    lunarDateOfBirth: '30/10/Mậu Ngọ',
    dateOfDeath: new Date('1938-03-15'),
    lunarDateOfDeath: '15/03/Mậu Dần',
    hometown: 'Làng Cổ Tích, Hà Nam',
    fatherId: gen2Child1Id,
    biography: 'Con trai thứ của Nguyễn Văn Trưởng, người có tài buôn bán.',
    generation: 3,
    isActive: true,
  },
  
  // Con của Nguyễn Văn Thứ
  {
    _id: generateId(),
    fullName: 'Nguyễn Văn Đức',
    gender: 'MALE',
    dateOfBirth: new Date('1860-02-15'),
    lunarDateOfBirth: '15/02/Canh Thân',
    dateOfDeath: new Date('1940-07-22'),
    lunarDateOfDeath: '22/07/Canh Thìn',
    hometown: 'Làng Cổ Tích, Hà Nam',
    fatherId: gen2Child2Id,
    biography: 'Con trai trưởng của Nguyễn Văn Thứ, người nổi tiếng về tài văn và võ.',
    generation: 3,
    isActive: true,
  },
  {
    _id: generateId(),
    fullName: 'Nguyễn Thị Mai',
    gender: 'FEMALE',
    dateOfBirth: new Date('1862-11-05'),
    lunarDateOfBirth: '05/11/Nhâm Tuất',
    dateOfDeath: new Date('1942-04-10'),
    lunarDateOfDeath: '10/04/Nhâm Ngọ',
    hometown: 'Làng Cổ Tích, Hà Nam',
    fatherId: gen2Child2Id,
    biography: 'Con gái của Nguyễn Văn Thứ, người nổi tiếng về y học cổ truyền.',
    generation: 3,
    isActive: true,
  },
  
  // Đời 4 (Thêm 6-8 người)
  {
    _id: generateId(),
    fullName: 'Nguyễn Văn Phúc',
    gender: 'MALE',
    dateOfBirth: new Date('1880-12-03'),
    lunarDateOfBirth: '03/12/Canh Thìn',
    dateOfDeath: new Date('1960-05-15'),
    lunarDateOfDeath: '15/05/Canh Tý',
    hometown: 'Làng Cổ Tích, Hà Nam',
    biography: 'Người có công lớn trong việc duy trì gia phả và phát triển làng quê.',
    generation: 4,
    isActive: true,
  },
  {
    _id: generateId(),
    fullName: 'Nguyễn Văn Thịnh',
    gender: 'MALE',
    dateOfBirth: new Date('1882-07-22'),
    lunarDateOfBirth: '22/07/Nhâm Ngọ',
    dateOfDeath: new Date('1962-09-08'),
    lunarDateOfDeath: '08/09/Nhâm Dần',
    hometown: 'Làng Cổ Tích, Hà Nam',
    biography: 'Người nổi tiếng về tài văn chương và giáo dục.',
    generation: 4,
    isActive: true,
  },
  {
    _id: generateId(),
    fullName: 'Nguyễn Thị Hoa',
    gender: 'FEMALE',
    dateOfBirth: new Date('1885-03-10'),
    lunarDateOfBirth: '10/03/Ất Dậu',
    dateOfDeath: new Date('1965-11-20'),
    lunarDateOfDeath: '20/11/Ất Tỵ',
    hometown: 'Làng Cổ Tích, Hà Nam',
    biography: 'Người nổi tiếng về đức hạnh và tài quản lý gia đình.',
    generation: 4,
    isActive: true,
  },

  // Đời 5 (Thêm 8-10 người)
  {
    _id: generateId(),
    fullName: 'Nguyễn Văn Tâm',
    gender: 'MALE',
    dateOfBirth: new Date('1910-01-15'),
    lunarDateOfBirth: '15/01/Canh Tuất',
    dateOfDeath: new Date('1990-07-22'),
    lunarDateOfDeath: '22/07/Canh Ngọ',
    hometown: 'Làng Cổ Tích, Hà Nam',
    biography: 'Người có công lớn trong thời kỳ kháng chiến.',
    generation: 5,
    isActive: true,
  },
  {
    _id: generateId(),
    fullName: 'Nguyễn Thị Lan',
    gender: 'FEMALE',
    dateOfBirth: new Date('1912-08-22'),
    lunarDateOfBirth: '22/08/Nhâm Tý',
    dateOfDeath: new Date('1995-11-15'),
    lunarDateOfDeath: '15/11/Ất Hợi',
    hometown: 'Làng Cổ Tích, Hà Nam',
    biography: 'Người nổi tiếng về tài nghệ thêu thùa và nữ công.',
    generation: 5,
    isActive: true,
  },
  {
    _id: generateId(),
    fullName: 'Nguyễn Văn Trí',
    gender: 'MALE',
    dateOfBirth: new Date('1915-03-10'),
    lunarDateOfBirth: '10/03/Ất Mão',
    dateOfDeath: new Date('1998-09-05'),
    lunarDateOfDeath: '05/09/Mậu Dần',
    hometown: 'Làng Cổ Tích, Hà Nam',
    biography: 'Người nổi tiếng về tài trí và đóng góp cho giáo dục.',
    generation: 5,
    isActive: true,
  },

  // Đời 6 (Thêm 10-12 người)
  {
    _id: generateId(),
    fullName: 'Nguyễn Văn Hùng',
    gender: 'MALE',
    dateOfBirth: new Date('1945-05-20'),
    lunarDateOfBirth: '20/05/Ất Dậu',
    hometown: 'Hà Nội',
    biography: 'Tiến sĩ kinh tế, người có nhiều đóng góp cho ngành kinh tế Việt Nam.',
    generation: 6,
    isActive: true,
  },
  {
    _id: generateId(),
    fullName: 'Nguyễn Thị Hạnh',
    gender: 'FEMALE',
    dateOfBirth: new Date('1948-10-30'),
    lunarDateOfBirth: '30/10/Mậu Tý',
    hometown: 'Hà Nội',
    biography: 'Bác sĩ y khoa, người có nhiều đóng góp cho ngành y tế.',
    generation: 6,
    isActive: true,
  },
  {
    _id: generateId(),
    fullName: 'Nguyễn Văn Thành',
    gender: 'MALE',
    dateOfBirth: new Date('1950-02-15'),
    lunarDateOfBirth: '15/02/Canh Dần',
    hometown: 'Hà Nội',
    biography: 'Kỹ sư xây dựng, người có nhiều công trình nổi tiếng.',
    generation: 6,
    isActive: true,
  },

  // Đời 7 (Thế hệ hiện tại - Thêm 12-15 người)
  {
    _id: generateId(),
    fullName: 'Nguyễn Minh Tuấn',
    gender: 'MALE',
    dateOfBirth: new Date('1975-12-03'),
    lunarDateOfBirth: '03/12/Ất Mão',
    hometown: 'Hà Nội',
    biography: 'Doanh nhân thành đạt trong lĩnh vực công nghệ.',
    generation: 7,
    isActive: true,
  },
  {
    _id: generateId(),
    fullName: 'Nguyễn Thị Hương',
    gender: 'FEMALE',
    dateOfBirth: new Date('1978-07-22'),
    lunarDateOfBirth: '22/07/Mậu Ngọ',
    hometown: 'Hồ Chí Minh',
    biography: 'Giáo sư đại học chuyên ngành kinh tế học.',
    generation: 7,
    isActive: true,
  },
  {
    _id: generateId(),
    fullName: 'Nguyễn Minh Đức',
    gender: 'MALE',
    dateOfBirth: new Date('1980-03-10'),
    lunarDateOfBirth: '10/03/Canh Thân',
    hometown: 'Đà Nẵng',
    biography: 'Kỹ sư phần mềm, người sáng lập công ty công nghệ nổi tiếng.',
    generation: 7,
    isActive: true,
  },
]; 